spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daraja_api
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver





mpesa:
  daraja:
    consumer-key: 5KDqT69447FELMLip2Oh1TZjUuicTdpv3PDvPG2xaJkOnWPe
    consumer-secret: GKPSnQ3O5cv6YsgPpCO9Bzbl2WsWEztxOdIzg9H5LHNvWCkfriACAk7BAsTAHWfM
    grant-type: client_credentials
    oauth-endpoint: https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials
